### ISSUE TITLE
Platform Configuration File

### ISSUE THREAD

**Issue by johnnavaj** [platformio/platform-shakti#3]
I have a doubt regarding the platform.ini. As part of the examples like hello program etc the values in platform.ini is static. How can i have my own custom platform.ini while creating a new project with the designated board? Do i have to add extra parameters to the board specification or other ?

**Comment by valeros** [comment]
Hi @johnnavaj ! You can pass custom values using the next command http://docs.platformio.org/en/latest/userguide/cmd_init.html#cmdoption-platformio-init-o

**Comment by johnnavaj** [comment]
next command as in ? Adding new configuration to the project?

**Comment by valeros** [comment]
I'm not sure I understand. Can you describe what parameters you are trying to add?

**Comment by johnnavaj** [comment]
Parameters like "upload_protocol" and "upload_port" for instance.

**Comment by valeros** [comment]
It's possible using CLI command:
```
pio init -d path_to_folder --board artix7_35t --project-option "upload_protocol=jlink" --project-option "upload_port=COM3"
```

**Comment by johnnavaj** [comment]
Alright will check it out. @valeros

**Comment by johnnavaj** [comment]
Closing this as Upload issue is fixed.
