### ISSUE TITLE
Custom Upload Command

### ISSUE THREAD

**Issue by johnnavaj** [platformio/platform-shakti#5]
Regarding the upload protocol statement for PIO , i have detailed the issue below.

**Observation 1** : With "upload_protocol=custom" I am able to upload and debug well.
![Debug-working-new](https://user-images.githubusercontent.com/31366212/62347439-549d9700-b517-11e9-89da-b61ee9827ea6.jpeg)

**Debugging the Program**
![Debugging-final](https://user-images.githubusercontent.com/31366212/62347569-c675e080-b517-11e9-93a9-88540fea654a.jpeg)

**Observation 2** : Without "upload_protocol=custom" it doesn't upload.
![upload not working](https://user-images.githubusercontent.com/31366212/62347659-0b017c00-b518-11e9-95ee-d1fc336ad379.jpeg)

What i feel is if we don't give the custom part, it tries to program flash instead.

**Comment by valeros** [comment]
I'm not sure you were able to upload your firmware using the `custom` protocol as there is no implementation for `UPLOADCMD` in this case, there was only `SUCCESS` message without proper uploading to the target. It's interesting why it works if you upload your code during debug session, but fails when you try to flash it directly over openocd as they are basically using the same elf file.

How do you usually upload code to the board?

**Comment by johnnavaj** [comment]
We use FTDI (USB-UART) enabled OpenOCD also the bitstream has ftdi enabled , so you can write directly with the help of GDB once the target is intialized in the openocd session.

**Comment by johnnavaj** [comment]
Yes as pointed out it uploads only in the debug section but i can't proceed to debug without doing the upload command.

**Comment by valeros** [comment]
You are using GDB even for a simple upload? 
Could you please open this file:
`~/.platformio/platforms/shakti/builder/main.py` 
and change line #150
```
 "-c", "program {$SOURCE} %s verify; shutdown;
```
to this one:
```
 "-c", "init; load_image {$SOURCE} %s reset; shutdown;"
```

**Comment by johnnavaj** [comment]
For load_image , reset works ? It will return invalid command for reset in the above case.

**Comment by valeros** [comment]
@johnnavaj Unfortunately I don't have this board to test, so I hoped that you would tell me.
Did it write the image? Could you try to remove reset command? What was printed in the log?

**Comment by johnnavaj** [comment]
![try](https://user-images.githubusercontent.com/31366212/62448748-1a85fc80-b786-11e9-9b80-8bc19d4e49a2.png)
 
Can you tell me what happens when you execute "Start Debbugging" so i can compare the two command line parameter execution phases.

**Comment by valeros** [comment]
The default workflow is the next:
- Launch OpenOCD gdb server
- Run GDB with the target firmware, connect GDB to that server and run the next commands:
```
target extended-remote :3333
thb main
monitor reset halt
load
monitor init
monitor reset halt
```
The only difference that uploading is handled on the GDB side.
Have you tried to remove `reset` command?
```
 "-c", "init; load_image {$SOURCE} %s; shutdown;"
```
From the picture above I see that you trying to upload while debugging, I'm not sure that this is allowed.

**Comment by johnnavaj** [comment]
My bad i started debugging after doing upload thats why its showing there. Otherwise its the same only .
 YAY! Removing the reset works. Thanks. 

But for monitor , where can replicate the continue command ?

**Comment by valeros** [comment]
```
But for monitor , where can replicate the continue command ?
```
What do you mean?

**Comment by johnnavaj** [comment]
Like for auto  executing the program and getting the output on the miniterm

**Comment by valeros** [comment]
As you saw, reset command doesn't work, so the only way is to reset the board and open terminal manually.

**Comment by johnnavaj** [comment]
Yep, talked to hardware team. So for now it can be written to TCM or RAM and Contunue Command will be executed in the debug session which in turn would produce O/P in the monitor. Will integrate qspi and test the flash write. Thanks a ton for your help.

**Comment by johnnavaj** [comment]
can i create a PR for updating the command for now ? to solve the custom upload command ? @valeros

**Comment by valeros** [comment]
Sure thing and feel free to close this issue if the problem is resolved.

**Comment by johnnavaj** [comment]
Sure.
