### ISSUE TITLE
Error: invalid ELF file, only 32bits files are supported

### ISSUE THREAD

**Issue by swathiparthiban96** [platformio/platform-shakti#7]
I get the following error while uploading hello world program to artix7_100t board

64 bit version of the riscv toolchain is used here.

![Platformio](https://user-images.githubusercontent.com/53891632/63015772-81ef2b00-beaf-11e9-854c-0f7ec64e5cbb.png)

**Comment by valeros** [comment]
Hi @swathiparthiban96 ! That's interesting, I suppose that problem occurs only with `artix_100t` board? Are you able to debug the board? @sathya281 @johnnavaj Where I can get `OpenOCD` package do you usually use without PlatformIO? I see there is one in `shakti-tools` repository, does it differ from the official OpenOCD fork for RISC-V platform?

**Comment by johnnavaj** [comment]
@valeros yes we use the openocd located in shakti-tools repository. Since that was not updated with in the latest framework of platformio ,for the time being we used to replace the openocd binary with the one in tools-openocd-riscv. And yes it differs from openocd where the  frame is inverted to Pseudo Tap for Simpler Hardware to Decode. If you can update the framework-shakti-sdk to the latest  commit it will be very helpful. So coming back to the issue i am seeing this for the first time! i never got issues with both boards .

**Comment by johnnavaj** [comment]
@valeros i am facing this error too now , the firmware elf created does not load via the openocd initiated through pio but gets loaded manually. Using same version of openocd for both(openocd used in shakti-tools).

**Comment by valeros** [comment]
@johnnavaj That's interesting, but it worked before right? Has anything changed since that moment?

**Comment by johnnavaj** [comment]
@valeros yes it was working fine before and no i haven't changed anything till the since last PR regarding upload command.

**Comment by valeros** [comment]
@johnnavaj  Let's switch to uploading hex image instead of elf. Please try the next `platformio.ini` file:
```
[env:artix7_100t]
platform = https://github.com/platformio/platform-shakti.git#feature/upload-hex-image
framework = shakti-sdk
board = artix7_100t
monitor_speed = 115200
```

**Comment by johnnavaj** [comment]
Yes hex image works @valeros could it be something that has changed on how elf images are handled?

**Comment by valeros** [comment]
@johnnavaj I think it's just an internal OpenOCD limitation.

**Comment by johnnavaj** [comment]
@valeros I checked the C code for OpenOCD (image.c in src folder) , looks like its taking in 64 type too, looks interesting. Anyways will work with hex now and look into ELF later. Can you update framework-shakti-sdk to the latest containing the shakti-tools soon ?

**Comment by valeros** [comment]
Hi @johnnavaj I've updated the sdk package. Please retest with the latest platform from development branch. 
```
[env:artix7_100t]
platform = https://github.com/platformio/platform-shakti.git
framework = shakti-sdk
board = artix7_100t
monitor_speed = 115200
```
Feel free to open a new issue in case there is any problem.
