### ISSUE TITLE
Monitor Speed

### ISSUE THREAD

**Issue by johnnavaj** [platformio/platform-shakti#8]
The monitor_speed(baudrate) is 19200 not 115200 for shakti.

**Comment by valeros** [comment]
What do you mean? Do we need something to change?

**Comment by johnnavaj** [comment]
The monitor_speed in platform.ini is 115200 by default,but as per shakti its 19200 hence the change is needed,

**Comment by valeros** [comment]
Where exactly is 115200 specified?

**Comment by johnnavaj** [comment]
My bad i checked a different platform.ini.
