### ISSUE TITLE
PlatformIO Documentation.

### ISSUE THREAD

**Issue by johnnavaj** [platformio/platform-shakti#9]
How can we submit documentation via ReadtheDocs? Is it by a PR filed through PlatfromIO-Docs repo ? or other ?

**Comment by ivankravets** [comment]
We have not added this dev/platform to our registry. Is it time now? If yes, then docs will be automatically generated in https://github.com/platformio/platformio-docs/tree/develop/platforms

**Comment by johnnavaj** [comment]
@ivankravets yes the pio as been tested accordingly for the fpga boards (artix 35T and 100T),Can you make sure framework-shakti-sdk as been updated to the latest commit ,if yes we can proceed .

**Comment by ivankravets** [comment]
Done! http://docs.platformio.org/en/latest/platforms/shakti.html

**Comment by johnnavaj** [comment]
Cool! Thanks a ton!
